// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA85AKkDiL8qTR7ALG7EvysnOVgOZXcigs',
    appId: '1:831731966839:web:3e309280ebd4f0506d3772',
    messagingSenderId: '831731966839',
    projectId: 'etkinlik-planlayici',
    authDomain: 'etkinlik-planlayici.firebaseapp.com',
    storageBucket: 'etkinlik-planlayici.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3jgVonpGrjE2l4pn1m05hEMY2BZ35hU',
    appId: '1:831731966839:android:a8dc823054815f7e6d3772',
    messagingSenderId: '831731966839',
    projectId: 'etkinlik-planlayici',
    storageBucket: 'etkinlik-planlayici.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1sOO5a_ghDgEpoa9oPIMvooikQmWtnKE',
    appId: '1:831731966839:ios:8d7691d3cc27dc5f6d3772',
    messagingSenderId: '831731966839',
    projectId: 'etkinlik-planlayici',
    storageBucket: 'etkinlik-planlayici.firebasestorage.app',
    iosBundleId: 'com.example.etkinlikPlanlayici',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1sOO5a_ghDgEpoa9oPIMvooikQmWtnKE',
    appId: '1:831731966839:ios:8d7691d3cc27dc5f6d3772',
    messagingSenderId: '831731966839',
    projectId: 'etkinlik-planlayici',
    storageBucket: 'etkinlik-planlayici.firebasestorage.app',
    iosBundleId: 'com.example.etkinlikPlanlayici',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA85AKkDiL8qTR7ALG7EvysnOVgOZXcigs',
    appId: '1:831731966839:web:440186e4e5b9389a6d3772',
    messagingSenderId: '831731966839',
    projectId: 'etkinlik-planlayici',
    authDomain: 'etkinlik-planlayici.firebaseapp.com',
    storageBucket: 'etkinlik-planlayici.firebasestorage.app',
  );
}
